[build]
target = "thumbv6m-none-eabi"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip RP2040 --always-print-stacktrace --catch-reset --catch-hardfault"

[unstable]
#build-std-features = ["panic_immediate_abort"]

# For host builds and STD targets
build-std = ["core", "alloc"]

[env]
DEFMT_LOG="info"
